#!/bin/sh
/bin/sed -i "s/:1000:1000:Phing:/:$PHING_UID:$PHING_GID:phing:/g" /etc/passwd
/bin/sed -i "s/:1000:phing/:$PHING_GID:phing/g" /etc/group
CMD="/usr/bin/php /opt/composer/vendor/bin/phing $@"
su -l phing -s /bin/sh -c "${CMD}"

